# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import _thread
import compare_dis

from PyQt5 import QtCore, QtGui, QtWidgets

# class Ui_Dialog(object):
#     def setupUi(self, Dialog):
#         Dialog.setObjectName("Dialog")
#         Dialog.resize(400, 300)
#         self.label = QtWidgets.QLabel(Dialog)
#         self.label.setGeometry(QtCore.QRect(130, 90, 191, 111))
#         font = QtGui.QFont()
#         font.setPointSize(14)
#         self.label.setFont(font)
#         self.label.setObjectName("label")
#
#         self.retranslateUi(Dialog)
#         QtCore.QMetaObject.connectSlotsByName(Dialog)
#
#     def retranslateUi(self, Dialog):
#         _translate = QtCore.QCoreApplication.translate
#         Dialog.setWindowTitle(_translate("Dialog", "弹窗"))
#         self.label.setText(_translate("Dialog", "行不行啊细狗"))
from PyQt5.QtWidgets import QMessageBox, QDialog

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(321, 236)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(mainWindow)
        self.pushButton.clicked.connect(self.begin_comp)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "initial_window"))
        self.label.setText(_translate("mainWindow", "基于人脸识别的远程打卡系统"))
        self.pushButton.setText(_translate("mainWindow", "开始打卡"))

    def begin_comp(self):
        global capture
        flag, inf,capture = compare_dis.compare_dis()
        _thread.start_new_thread(release, ())
        # name = names[0]
        # fg = jud_ctrl.jud_ctrl(name)
        if flag:
            inf = json.loads(inf)
            name = inf['name']
            isAdmin = inf['isAdmin']=='true'
            if not isAdmin:
                msgBox = QMessageBox()
                msgBox.setStyleSheet("QLabel{"
                                     "min-width: 200px;"
                                     "min-height: 70px; "
                                     "font:18px"
                                     "}")
                msgBox.setWindowTitle("欢迎！")
                msgBox.setText(name + "先生，打卡成功")
                msgBox.exec()

            else:
                msgBox = QMessageBox()
                msgBox.setStyleSheet("QLabel{"
                                     "min-width: 200px;"
                                     "min-height: 80px; "
                                     "font:18px"
                                     "}")
                msgBox.setWindowTitle("欢迎！")
                msgBox.setText('您好，管理员' + name + "先生")
                msgBox.exec()

                from pyqt import ctrl_Dia
                ctrl_ui = QDialog()
                c_win = ctrl_Dia.Ui_ctrl_win()
                c_win.setupUi(ctrl_ui)
                ctrl_ui.exec()

def release():
    capture.release()