# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_inf_Dia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(254, 170)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.input_but)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "add_inf"))
        self.label.setText(_translate("Dialog", "姓名为："))
        self.label_2.setText(_translate("Dialog", "权限为："))
        self.pushButton.setText(_translate("Dialog", "录入"))

    def input_but(self):
        name = self.lineEdit.text()
        author = self.lineEdit_2.text()
        msgBox = QMessageBox()
        msgBox.setStyleSheet("QLabel{"
                             # "min-width: 200px;"
                             # "min-height: 80px; "
                             "font:18px"
                             "}")
        msgBox.setWindowTitle("注意")
        msgBox.setText('确定要录入该人吗？')

        yes = msgBox.addButton('确认', QMessageBox.YesRole)
        no = msgBox.addButton('取消', QMessageBox.NoRole)

        msgBox.setIcon(1)

        msgBox.exec()

        msgBox1 = QMessageBox()
        msgBox1.setStyleSheet("QLabel{"
                                    # "min-width: 200px;"
                                    # "min-height: 80px; "
                              "font:18px"
                        "}")
        msgBox1.setWindowTitle("注意")
        msgBox1.setText('按下s键保存图片\n按下q键退出')
        msgBox1.exec()

        if msgBox.clickedButton() == yes:
            from .add_inf import add_inf
            try:
                capture = add_inf(name, author)
                msgBox = QMessageBox()
                msgBox.setStyleSheet("QLabel{"
                                     # "min-width: 200px;"
                                     # "min-height: 80px; "
                                     "font:18px"
                                     "}")
                msgBox.setWindowTitle("成功")
                msgBox.setText('录入成功！')
                msgBox.setIcon(1)
                msgBox.exec()
            except Exception as e:
                print(e)
                msgBox = QMessageBox()
                msgBox.setStyleSheet("QLabel{"
                                     # "min-width: 200px;"
                                     # "min-height: 80px; "
                                     "font:18px"
                                     "}")
                msgBox.setWindowTitle("失败")
                msgBox.setText('信息录入失败')
                msgBox.setIcon(3)
                msgBox.exec()
            finally:
                try:
                    capture.release()
                except:
                    pass