# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_Dia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(252, 101)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 60, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.del_but)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "del_inf"))
        self.label.setText(_translate("Dialog", "姓名为："))
        self.pushButton.setText(_translate("Dialog", "删除"))

    def del_but(self):
        msgBox = QMessageBox()
        msgBox.setStyleSheet("QLabel{"
                             # "min-width: 200px;"
                             # "min-height: 80px; "
                             "font:18px"
                             "}")
        msgBox.setWindowTitle("确认")
        msgBox.setText('是否删除该用户？')
        yes = msgBox.addButton('确认', QMessageBox.YesRole)
        no = msgBox.addButton('取消', QMessageBox.NoRole)
        msgBox.setIcon(1)
        msgBox.exec()

        if msgBox.clickedButton() == yes:
            name = self.lineEdit.text()
            _response = requests.get(
                url='http://43.142.162.144:5000/deleteUser',
                params={'id': name}
            )
            res = _response.text

            if res == 'not found':
                msgBox = QMessageBox()
                msgBox.setStyleSheet("QLabel{"
                                     # "min-width: 200px;"
                                     # "min-height: 80px; "
                                     "font:18px"
                                     "}")
                msgBox.setWindowTitle("失败")
                msgBox.setText('未找到该人员！')
                msgBox.setIcon(3)
                msgBox.exec()

            else:
                msgBox = QMessageBox()
                msgBox.setStyleSheet("QLabel{"
                                     # "min-width: 200px;"
                                     # "min-height: 80px; "
                                     "font:18px"
                                     "}")
                msgBox.setWindowTitle("成功")
                msgBox.setText('已删除该人员！')
                msgBox.setIcon(1)
                msgBox.exec()
